### ISSUE TITLE
Assumes that all "Enumeration" Types have an integer BaseType and raises an Exception otherwise

### ISSUE THREAD

**Issue by thomasheritage** [sandflow/regxmllib#119]
Sample output (from an old version of the code, but the relevant parts don't look like they've changed):

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "Main"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:740)
        at java.lang.Integer.decode(Integer.java:1197)
        at com.sandflow.smpte.regxml.dict.importers.RegisterImporter.fromRegister(RegisterImporter.java:389)
        at com.sandflow.smpte.tools.XMLRegistersToDict.main(XMLRegistersToDict.java:86)
```

This occurs when processing a Types Register that contains a Type with TypeKind "Enumeration" where a Facet Value is not an Integer. This will legitimately occur in the Types Register when the BaseType of the Type is a non-Integer Type.

SMPTE ST 2003:2012 Section 4.2.2 is clear that Enumerations can have any BaseType. This also the practical approach taken in managing the Types Register, as documented at https://registry.smpte-ra.org/view/draft/docs/Register%20(Types)/Type%20Kinds/Enumeration/

Therefore, regxmllib needs to expect such types when processing a Types Register and not raise an Exception.

However, SMPTE ST 2001-1:2013 Section 6.1.6 is clear that an Enumeration always has integer values.

Perhaps the best approach is for regxmllib to simply ignore any entries in the Types Register which cannot be mapped to Reg-XML.

**Comment by palemieux** [comment]
> An “Enumeration” Type can have any BaseType.

Well, how is _any BaseType_ supposed to be represented as an `xs;string` which is the type of the facet value in the XML registers?

> Therefore, regxmllib needs to expect such types when processing a Types Register and not raise an Exception.

Yes. This should be fixed.

**Comment by palemieux** [comment]
@thomasheritage Please review PR #120

**Comment by thomasheritage** [comment]
Thanks a lot for the quick alteration -- I'll test shortly.

> Well, how is any BaseType supposed to be represented as an xs:string which is the type of the facet value in the XML registers?

As per [the Registers docs](https://registry.smpte-ra.org/view/draft/docs/Register%20(Types)/Type%20Kinds/Enumeration/) this is currently only defined for a couple of cases -- in other cases the representation is not guaranteed to take any particular form. The only case so far is an Enumeration with a BaseType of string so this isn't an issue.

**Comment by palemieux** [comment]
>  in other cases the representation is not guaranteed to take any particular form. 

It should therefore be forbidden until someone makes the effort to propose something.

> The only case so far is an Enumeration with a BaseType of string so this isn't an issue.

This is not documented anywhere, e.g. at  [the Registers docs](https://registry.smpte-ra.org/view/draft/docs/Register%20(Types)/Type%20Kinds/Enumeration/)
