### ISSUE TITLE
Memory leak in KLVStream.cpp

### ISSUE THREAD

**Issue by ErikCJohansson** [sandflow/regxmllib#129]
The function readBERLength allocates up to 8 bytes which are never free'd. Propose to use a fixed buffer size of 8 bytes instead.

[patch.gz](https://github.com/sandflow/regxmllib/files/2382733/patch.gz)

**Comment by palemieux** [comment]
Yes. Offending line: https://github.com/sandflow/regxmllib/blob/106a26a504871e8a614a0cdfce6d756b5315b734/regxmllib/src/main/cpp/com/sandflow/smpte/klv/KLVStream.cpp#L105

**Comment by palemieux** [comment]
@ErikCJohansson Please review the PR at https://github.com/sandflow/regxmllib/pull/131
