### ISSUE TITLE
Add tool to validate EssenceDescriptor in CPL

### ISSUE THREAD

**Issue by palemieux** [sandflow/regxmllib#13]
Include command line option to remove namespaces from Essence Descriptor

**Comment by palemieux** [comment]
See https://imf.sandflow.com/validate

**Comment by IMFTool** [comment]
Hi Pierre,

The tool complains about the RFC5646LanguageTagList in the attached CPL, but I think it's correct. Please advise.

Best,
Wolfgang

[CPL_144cd254-1ca3-4066-bb17-36398511fc5b.xml.zip](https://github.com/sandflow/regxmllib/files/543106/CPL_144cd254-1ca3-4066-bb17-36398511fc5b.xml.zip)

**Comment by palemieux** [comment]
The RFC5646LanguageTagList element was erroneously omitted from the DCTimedTextDescriptor in published versions of the registers [1].

[1] https://kws.smpte.org/kws/groups/30mr10wg-def/email/archives/201609/dates/154083

The master branch at https://github.com/sandflow/IMF corrects this in the meantime.

**Comment by palemieux** [comment]
> The tool complains about the RFC5646LanguageTagList in the attached CPL, but I think it's correct. Please advise.

https://imf.sandflow.com/validate updated with the latest registers
