### ISSUE TITLE
Additional memory leaks

### ISSUE THREAD

**Issue by palemieux** [sandflow/regxmllib#130]
`def_copy` not freed if addition to dictionary fails at

https://github.com/sandflow/regxmllib/blob/9378fb51ba2efe574cd5a5ccc9ea95d4b7a09e99/regxmllib/src/main/cpp/com/sandflow/smpte/regxml/dict/MetaDictionary.cpp#L87

`def_copy` not freed if addition to dictionary fails at

https://github.com/sandflow/regxmllib/blob/9378fb51ba2efe574cd5a5ccc9ea95d4b7a09e99/regxmllib/src/main/cpp/com/sandflow/smpte/regxml/dict/MetaDictionary.cpp#L107

`def_copy` allocated but never used at

https://github.com/sandflow/regxmllib/blob/9378fb51ba2efe574cd5a5ccc9ea95d4b7a09e99/regxmllib/src/main/cpp/com/sandflow/smpte/regxml/dict/MetaDictionary.cpp#L121

`ft` and `parser` never deleted at `MetaDictionaryTest.cpp`

**Comment by ErikCJohansson** [comment]
I searched for 'new ' to take a look at any additional allocations. I see that the pattern 'throw new' is used in several places. I believe this is a mistake as it will throw a pointer to a dynamically allocated object, which will leak unless there is a corresponding 'catch' with the correct type that calls 'delete' on the thrown object.

**Comment by palemieux** [comment]
> throw new

Ah. Good catch. Leftover from Java conversion.
