### ISSUE TITLE
Fails to build using gcc 8.5

### ISSUE THREAD

**Issue by radford-for-smpte** [sandflow/regxmllib#151]
Tested using the gcc that ships w/ both CentOS 8 and 9. You can reproduce using this simple `Dockerfile`:

```Dockerfile
FROM rockylinux:8

RUN yum install -y epel-release
RUN yum install -y cmake3 xerces-c-devel gcc gcc-c++ tar gzip make

ENV VERSION=1.1.4

RUN curl -L https://github.com/sandflow/regxmllib/archive/$VERSION.tar.gz | tar -z -x -f - && \
    cd regxmllib-$VERSION && \
    cmake3 . && \
    make
```

and the command `docker build .`

See error output here:

[log.txt](https://github.com/sandflow/regxmllib/files/12871980/log.txt)

**Comment by palemieux** [comment]
Did you try `-std=c++11`?

**Comment by palemieux** [comment]
Can you attach `xerces-c/include/xercesc/util/Xerces_autoconf_config.hpp`?

**Comment by palemieux** [comment]
Ok, so the basic issue is that modern OSes require C++ > 98, so to we cannot require `CXX_STANDARD == 98`.

We should instead test the library in an environment that supports `CXX_STANDARD == 98`.
