### ISSUE TITLE
Missing Target Set UL -- Warnings

### ISSUE THREAD

**Issue by thomasheritage** [sandflow/regxmllib#25]
When processing smpte_registers-bbc_rd_db_exports-201412092156 I got quite a few warnings of the form:

```
Jan 08, 2015 3:26:44 PM com.sandflow.smpte.regxml.dict.importer.XMLRegistryImporter fromRegister
WARNING: Missing Target Set UL at Facet null for Type urn:smpte:ul:060e2b34.01040101.05010c00.00000000
```

What does this mean? Are these warnings genuine? Is there a problems with the Registers entries?

**Comment by palemieux** [comment]
These warnings were generated based on an earlier mapping of the Types Register, which assumed that the Target Set UL was stored in the UL field of the Facet instead of the Value field of the Facet.

Should be fixed.
