### ISSUE TITLE
Adjust reg.xsd namespace

### ISSUE THREAD

**Issue by thomasheritage** [sandflow/regxmllib#28]
The namespace should be something like ```http://www.smpte-ra.org/schemas/2001-1c/2013``` (we may also want a suffix on this (but "metadict" would not be appropriate)). Not sure if it should be 2013 or not...

**Comment by thomasheritage** [comment]
Of course all the XSDs and XMLs auto generated will need to use the new namespace as well

**Comment by palemieux** [comment]
I see risk in guessing what the ultimate namespace selected by SMPTE will be. Instead I propose to use the ad hoc namespace http://sandflow.com/schemas/SMPTEST2001-1/baseline . It should have no impact on users merely using the schemas for validation.

**Comment by palemieux** [comment]
Fixed in 3a2bb396964e82594cea4f0f5e4c1fba21a81005
