### ISSUE TITLE
applyRule5_12 does not handle 1-byte character strings (ISO-7)

### ISSUE THREAD

**Issue by palemieux** [sandflow/regxmllib#31]
Both UTF-16BE and ISO-7 (e.g. RFC5646LanguageCode) are present in MXF file.

Add switch to applyRule5_12() based on  elementType of String Definition.

**Comment by thomasheritage** [comment]
Note that a "Character" may also appear elsewhere (i.e. not always in a "String") e.g. standalone; as an item in a StringArray; etc.
