### ISSUE TITLE
Stop processing a String value at the first null terminator

### ISSUE THREAD

**Issue by thomasheritage** [sandflow/regxmllib#51]
We've seen this sort of error on a few files:
```
-:319: parser error : xmlParseCharRef: invalid xmlChar value 0
<r1:URL>/data/ingex_hd_test/cache/creating/BBD999999121.mxf&#0;&#0;&#0;&#0;&#0;&
                                                               ^
```
This is reported once for every zero value (a byte value of zero is not a permitted character in XML).

SMPTE ST 377-1:2011 states:
> The number of bytes allocated to this string is given by the KLV encoding. There is no requirement to terminate each string with a zero or other special value. However, if the length of the String information is less than the space allocated, the string shall be terminated with a zero value. 

This means that the decoder must not expect to see a null terminator. However, if it does see one then it must discard that null terminator and all other data after it (which could, or could not, be null values).

**Comment by palemieux** [comment]
> However, if the length of the String information is less than the space allocated, the string shall be terminated with a zero value.

I thought "a" zero value meant "one" zero value. Thoughts?

**Comment by mglanville** [comment]
Hi - I work with Tom.

A single zero value terminates the string when an MXF decoder is reading the file. Hence any bytes after that zero value can be ignored by a decoder. I don't think ST 377-1 is imposing a restriction on the data that can be present in a string in an MXF file, just specifying exactly how that string data shall be interpreted by a decoder.

Our interpretation is that any of these (when stored in MXF as string type):
`helloworld&#0;&#0;&#0;&#0;&#0;`
`helloworld&#0;`
`helloworld`
`helloworld&#0;&#0;hello`
are decoded as this:
`helloworld`
