### ISSUE TITLE
Dot not warn about inability to resolve references to Groups which do actually exist

### ISSUE THREAD

**Issue by thomasheritage** [sandflow/regxmllib#52]
These four warnings (given when building meta-dictionaries) are unexpected because the Groups that are being referenced do actually exist:
```
Jun 15, 2015 5:55:04 PM com.sandflow.smpte.regxml.XMLSchemaBuilder applyRule6_13
WARNING: Cannot resolve reference type urn:smpte:ul:060e2b34.027f0101.0c010101.01010300 for definition urn:smpte:ul:060e2b34.01040101.05022b00.00000000.
Jun 15, 2015 5:55:04 PM com.sandflow.smpte.regxml.XMLSchemaBuilder applyRule6_13
WARNING: Cannot resolve reference type urn:smpte:ul:060e2b34.027f0101.0c010101.01010800 for definition urn:smpte:ul:060e2b34.01040101.05022c00.00000000.
Jun 15, 2015 5:55:04 PM com.sandflow.smpte.regxml.XMLSchemaBuilder applyRule6_13
WARNING: Cannot resolve reference type urn:smpte:ul:060e2b34.027f0101.0c010101.01010400 for definition urn:smpte:ul:060e2b34.01040101.05022d00.00000000.
Jun 15, 2015 5:55:04 PM com.sandflow.smpte.regxml.XMLSchemaBuilder applyRule6_14
WARNING: Cannot resolve reference type urn:smpte:ul:060e2b34.027f0101.0c010101.01010300 for definition urn:smpte:ul:060e2b34.01040101.05022b00.00000000.
```

**Comment by palemieux** [comment]
The types refer to Groups that do not have a KLV syntax, and thus cannot be handled by RegXML. Thoughts?

**Comment by thomasheritage** [comment]
I suppose that if you’re ignoring groups with no (and / or inappropriate) KLV Syntax values then you should also ignore all metadata entries which directly, or indirectly, depend upon them: then these warnings would not appear for these Types.

**Comment by palemieux** [comment]
Right now only KLV Groups are imported into the metadictionary, so they are gone by the time the dangling reference in Type is encountered. Maybe the right approach is to tentatively import the non-KLV groups, and then prune all entries that reference them before pruning them as well.

Is this a blocker or merely an annoyance?

**Comment by thomasheritage** [comment]
Your suggested approach sound viable.
I would categorise this as just an annoyance not a blocker.

**Comment by palemieux** [comment]
See PR #90
