### ISSUE TITLE
zero-pad elements of timestamps

### ISSUE THREAD

**Issue by mglanville** [sandflow/regxmllib#54]
Output when parsing `AS11_DPP_HD_EXAMPLE_1.mxf`:
```
<r6:UKDPP_Completion_Date>2014- 2- 6T 0: 0: 0.0Z</r6:UKDPP_Completion_Date>
```

I was expecting:
```
<r6:UKDPP_Completion_Date>2014-02-06T00:00:00.0Z</r6:UKDPP_Completion_Date>
```

**Comment by palemieux** [comment]
Bug introduced in https://github.com/sandflow/regxmllib/commit/8f134805a89430fcd65ea1ad9618844bad018af5

**Comment by palemieux** [comment]
Note that regxmllib assumes that fraction = msec/4 according to 377-1
