### ISSUE TITLE
AUID Problems

### ISSUE THREAD

**Issue by thomasheritage** [sandflow/regxmllib#68]
The AUID class in `AUID.java` has at least two problems (some thorough testing of this class would be advisable to make sure there are no other issues):
* In `toString()`, for UUIDs, shouldn't you simply do `return asUUID().toString();`? As it stands the two halves of the UUID are not swapped back before conversion to a string.
* In `isUL()` the bitwise AND operation is masking the wrong bit. Use `& 0x80` instead.

**Comment by palemieux** [comment]
Adding unit tests would be most welcome.
