### ISSUE TITLE
Update to match modified exception relating to ProductReleaseType

### ISSUE THREAD

**Issue by thomasheritage** [sandflow/regxmllib#71]
See [this page](https://gitlab.com/thomas.heritage/30mr10_registers/wikis/mxf-implementation-notes#productreleasetype-is-an-enumeration-of-basetype-uint16-in-mxf) for details – the change is that the ProductReleaseType may be either UInt8 or UInt16 in real MXF files.

**Comment by palemieux** [comment]
The current code assumes UInt16 but accepts UInt8, so should work -- with a warning.
