### ISSUE TITLE
Add support for indirect type

### ISSUE THREAD

**Issue by akharkev** [sandflow/regxmllib#74]
Trying to process an MXF with properties of indirect type triggers the following error:

    Jan 11, 2016 7:17:44 PM com.sandflow.smpte.tools.RegXMLDump main
    SEVERE: Indirect type not supported.

A zipped MXF sample can be found here: http://cutpi.com/i5y (MD5: 9cd6b524bbe7cf12af40d5870cc932e7)

There's no formal definition of how indirect type values are represented in MXF files. [AAF SDK](http://aaf.sourceforge.net) stores a value of MXF Local Set that has indirect type as 3 components:

    Name            Type            Size            Value
    ----            ----            ----            -----
    Byte Order      UInt8           1 byte          0x4c ('L') - Little endian
                                                    0x42 ('B') - Big endian
    Actual Type     IDAU            16 bytes        Type UID
    Actual Value    As specified    As specified    Value of Actual Type
                    by Actual Type  by Actual Type

For description of IDAU see a recent revision of ST377.

TaggedValue is probably the most common use of indirect type. TaggedValues are lazy man's properties as they originally didn’t require formal definitions. TaggedValue is defined by AAF data model and represents a name-value pair where the value property has indirect type. Indirect type means that a property has its type specified in each instance. It's sort of AAF's version of a variant type.

Here's an MXFDump's dump of a TaggedValue object. The object has 3 properties, the one called 'Value' has indirect type and this instance stores a 4-byte integer.

    [ K = AAFTaggedValue ( 000000000001d806 )
    06.0e.2b.34.02.53.01.01.0d.01.01.01.01.01.3f.00, L =         71 (47) ]
      [ k = InstanceUID
      3c.0a, l =    16 (0010) ]
       1d820           a6 7a b7 b8 f8 51 4e 41 b1 bf 09 8a 84       .z...QNA.....
       1d830  e8 b9 2a                                           ..*
      [ k = Value
      50.03, l =    21 (0015) ]
       1d830                       4c 00 07 01 01 00 00 00 00           L........
       1d840  06 0e 2b 34 01 04 01 01 01 00 00 00                ..+4........
      [ k = Name
      50.01, l =    22 (0016) ]
       1d850  00 5f 00 44 00 4f 00 4d 00 49 00 4e 00 41 00 4e    ._.D.O.M.I.N.A.N
       1d860  00 43 00 45 00 00                                  .C.E..

**Comment by palemieux** [comment]
Could a sample file be provided?

**Comment by akharkev** [comment]
There's a link in the bug report.

**Comment by palemieux** [comment]
Thanks. Could the file ultimately be added to the regxmllib unit tests, which are released as part of the regxmllib under BSD license.

**Comment by akharkev** [comment]
Yes, the provided sample MXF file can be released as part of this project.

**Comment by palemieux** [comment]
Does the byte order apply to the Value field only or the Actual Type field as well?

**Comment by palemieux** [comment]
In fact, is the byte order always the same in practice?

**Comment by akharkev** [comment]
The byte order applies to both the Value field and the Actual Type field.

I believe that in practice the byte order is always the same. AAF SDK is the only source of indirect type values and it uses the platform's native byte order to store them. I am not aware of AAF SDK being used to generate MXF on platforms that are not little endian and I haven't seen MXF with the Byte Order field other than 0x4c.

**Comment by palemieux** [comment]
Revised sample file with correct ByteOrder: http://cutpi.com/7m2.

**Comment by palemieux** [comment]
If byte order is 'littleEndian', is Actual Type (IDAU) written as a sequence of bytes, in which case byte order does not matter, or as a record of integers, in which case byte order matters?

**Comment by palemieux** [comment]
Output based on PR #85.

[inderect-type-properties.txt](https://github.com/sandflow/regxmllib/files/367137/inderect-type-properties.txt)

In particular, note the indirect value at:

```
            <r0:TaggedValue>
              <r1:InstanceID>urn:uuid:a5628879-e515-47e3-9bbd-c702662a77d2</r1:InstanceID>
              <r1:IndirectValue>
                <!--No definition found for indirect type with AUID urn:smpte:ul:0e062b34.01040101.01100200.00000000.-->
              </r1:IndirectValue>
              <r1:Tag>UNC Path</r1:Tag>
            </r0:TaggedValue>
```
