### ISSUE TITLE
Elements/Properties should not be "unknown" based on their defined Group membership

### ISSUE THREAD

**Issue by thomasheritage** [sandflow/regxmllib#81]
If I create a Reg-XML file for [AS11_X2_WIP_c885bcc_Example_1.mxf](https://myshare.app.box.com/files/0/f/6610067561) using the test Registers (and code) included in a61b3ab9 then two Elements / properties are reported as "unknown". One of these genuinely is unknown (according to these Registers). The details of the other one are:
```
INFO: Unknown property UL = urn:smpte:ul:060e2b34.0101010d.06010104.05410100 at group TextBasedFramework
```

This Element is in Elements.xml and so can be processed. I believe the reason it is not processed is that in Groups.xml it is not listed as a member of the Group `TextBasedFramework`. (note: this is actually an error in the Registers which will shortly be fixed anyway in #80 &ndash; but this does not change what is being reported in this issue)

**"Known" Elements / properties should be processed regardless of whether the code _expected_ to find them in the Group or not.**

It might still be useful to generate an "info" message because the user might be interested to know that a Group has been extended with additional Element(s).

**Comment by thomasheritage** [comment]
It's worth noting that the AS-11 X2 Example MXF file that I linked to was produced from a Work In Progress (WIP) version of the Specification and so should not be considered as a golden / reference file. The Reg-XML files provided in the same Box folder were produced using a patched version of regxmllib using modified Registers.

**Comment by palemieux** [comment]
Re-reading ST 2001-1, it looks like a Property (as defined in a MetaDictionary) must be a "Member Of" of a Class. Therefore regxmllib currently ignores entries in the Elements register that are not referenced in the Groups register.

How would Class-less entries be represented in a MetaDictionary?

**Comment by thomasheritage** [comment]
You're right &ndash; this is a good point.

So, I think the situation is as follows:
* The idea is that the Group in which an Element appears is conceptually part of the definition of the Element
* This explains why "Member Of" is mandatory
* This also explains why Elements are not supposed to be used in Groups other than the one in which they were designed to appear (we know that there are exceptions to this in reality, but still this was the original design, at least for AAF/MXF)
* So, Elements in the Registers _should_ be added to Registers Groups entries (by editing them) wherever the information is available (regardless of who created each Element / Group in question) because:
  * really its Group membership is part of the definition of the Element
  * this is practically necessary to make Reg-XML work

So the solution to this issue could be as simple as: edit the Registers to make them correct.

**Comment by palemieux** [comment]
>edit the Registers to make them correct.

Yes.
