### ISSUE TITLE
Optionally read preface from Footer Partition

### ISSUE THREAD

**Issue by thomasheritage** [sandflow/regxmllib#84]
Perhaps this is already possible? If files are not Closed and Complete then the Footer Metadata can be much more useful than the Header Metadata. Therefore it would be very useful to be able to choose to read the Preface from the Footer instead.

**Comment by palemieux** [comment]
Can this process be automatic, i.e. if the Header  Partition is incomplete and/or open, then the Footer Partition is sought and assumed to be complete and closed?

**Comment by thomasheritage** [comment]
It's probably useful to be able to manually select any Header Metadata within the file (in any Partition) and convert it to Reg-XML (it could default to just using the Header Metadata in the Header Partition). However, also having an automated mode which chooses the most "useful" metadata based on closed/complete could also be of benefit.

**Comment by palemieux** [comment]
Is there an accepted XML structure to store Header Metadata dumped from multiple partitions?

**Comment by thomasheritage** [comment]
I'm not sure if anyone's tried to do that before. It might be easier and safer / less confusing just to have one XML file for each set of Header Metadata that was extracted from the MXF file. It would then be easier to, for example, diff them in order to compare instances of Header Metadata.
